/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import 'three'
import React, { useRef} from 'react'
import { useLoader} from 'react-three-fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'

const Model=(props:JSX.IntrinsicElements['group'])=> {
  const group = useRef()
  const { nodes } = useLoader(GLTFLoader, '/scene.gltf')

  return (
    <group ref={group} {...props} dispose={null}>
      <scene name="Scene">
        <primitive object={nodes.PointLight} />
        <mesh
          material={nodes.Torus.material}
          geometry={nodes.Torus.geometry}
          name="Torus"
          position={[2.37, 1.97, 2.59]}
        />
      </scene>
    </group>
  )
}

export default Model
